name: Rust maintenance

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Format all
        run: cargo fmt --all

      - name: Clippy fix
        run: cargo clippy --fix --lib -p textforge

      - name: Test
        run: cargo test --features test_access,bytecode --release

      - name: Commit maintenance changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .

          if git diff --cached --quiet; then
            echo "No maintenance changes to commit."
          else
            git commit -m "Executed workflow maintenance"
            git push
          fi

      - name: Publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: cargo publish
